version: "3.8"

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: juckbox
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: qwert@12345
    ports:
      - "6543:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
