// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: Muscians.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const musiciansById = `-- name: MusiciansById :one
SELECT musician_id, musician_name, musician_type FROM Musicians WHERE musician_id = $1
`

func (q *Queries) MusiciansById(ctx context.Context, musicianID uuid.UUID) (Musician, error) {
	row := q.db.QueryRow(ctx, musiciansById, musicianID)
	var i Musician
	err := row.Scan(&i.MusicianID, &i.MusicianName, &i.MusicianType)
	return i, err
}
