// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: MusicAlbum.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getMusicAlbumsById = `-- name: GetMusicAlbumsById :one
SELECT album_id, album_name, release_date, genre, price, description FROM MusicAlbums WHERE album_id = $1
`

func (q *Queries) GetMusicAlbumsById(ctx context.Context, albumID uuid.UUID) (Musicalbum, error) {
	row := q.db.QueryRow(ctx, getMusicAlbumsById, albumID)
	var i Musicalbum
	err := row.Scan(
		&i.AlbumID,
		&i.AlbumName,
		&i.ReleaseDate,
		&i.Genre,
		&i.Price,
		&i.Description,
	)
	return i, err
}
