// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetMusicAlbumsById(ctx context.Context, albumID uuid.UUID) (Musicalbum, error)
}

var _ Querier = (*Queries)(nil)
